### ISSUE TITLE
Sass&Compass dependency

### ISSUE THREAD

**Issue by JelteMX** [mendix/ux-theming#1]
Need to check whether or not you need to install Sass (& Compass) when using Gulp.

**Comment by JelleDekker** [comment]
gulp-sass doesn't have the shade & tint functions from Compass. So when using Gulp you get invalid CSS. Probably should be using either gulp-compass, or manually add the shade and tint functions to the scss

**Comment by JelteMX** [comment]
I'm not sure if UX wants to continue using Compass. (I'd rather avoid it because it can be quite a hassle to use Compass included). I'll check if necessary. 

Can you tell me which functions are used? (I think this really depends on the themes)

**Comment by JeroenKesteloo** [comment]
I think only shade & tint are dependent on compass. Using darken & lighten in stead is possible. Just make sure you replace all shades and tints.

**Comment by JelleDekker** [comment]
styles/lib/base/_variables uses shade & tint all the time. 

Adding the following to the scss works:
```
@function tint($color, $percent){
  @return mix(white, $color, $percent);
}

@function shade($color, $percent){
  @return mix(black, $color, $percent);
}
```
found here: [https://github.com/sturobson/Sassifaction-Gulp/blob/master/dev/sass/base/mixins/_tint-and-shade.scss](url)

Or rewriting all the tint/shade to mix(white/black, $color, $percent) would also work I guess
