### ISSUE TITLE
Mendix 8 Destination Change

### ISSUE THREAD

**Issue by simo101** [mendix/ux-theming#13]
Hi,
In Mendix 8 the destination folder structure for styles has changed.

I fixed this in my gulp file by changing this line of code:
`deploymentCssFolder = deploymentFolder + '/css/';`

to:
`    deploymentCssFolder = deploymentFolder + '/web/css/';`

**Comment by JelteMX** [comment]
Documented here: https://github.com/mendix/ux-theming#mendix-8-caveats
