### ISSUE TITLE
gulpfile fails on 8.0.0 beta 3

### ISSUE THREAD

**Issue by mblase75** [mendix/ux-theming#14]
8.0.0 beta 3 moves the css and sass files into two subfolders of theme/styles -- 'native' and 'web' -- and as a result the current gulpfile fails with an error like this:

> Error: ENAMETOOLONG: name too long, stat 'C:\Users\<myname>\Documents\Mendix\<projectname>\theme\styles\sass\theme\styles\sass\theme\styles\sass\theme\styles\sass\theme\styles\sass\theme\styles\sass\theme\styles\sass\theme\styles\sass\theme\styles\sass\theme\st <etc>

**Comment by gitsno** [comment]
This is still happening on the Mendix 8.0.0 release. A workaround (which is now documented in the README.md for this repo) is to edit the style folder variables in Gulpfile.js, for web development (sorry, not sure about mobile) change

```
// What is the name of the style folder in this theme folder?
var sourceStyleFolder = 'theme/styles';

// What is the name of the style folder in the deployment folder?
var deploymentStyleFolder = 'styles';
```
to
```
// What is the name of the style folder in this theme folder?
var sourceStyleFolder = 'theme/styles/web';

// What is the name of the style folder in the deployment folder?
var deploymentStyleFolder = 'styles/web';
```

**Comment by JelteMX** [comment]
Thanks @gitsno, I overlooked this issue on Github. Indeed, the workaround is in the README, find it here: https://github.com/mendix/ux-theming#mendix-8-caveats

Closing the issue
