### ISSUE TITLE
gulp dev  command gives error in mendix 8.1

### ISSUE THREAD

**Issue by Abhijitbha** [mendix/ux-theming#15]
gulp dev  command gives error in mendix 8.1

s\theme\styles\sass'
[15:35:30] 'dev' errored after 40 s
[15:35:30] The following tasks did not complete: browsersync
[15:35:30] Did you forget to signal async completion?

**Comment by siddiqui111** [comment]
This is due to new folder structure in Mendix 8. If you make below changes to gulp.js file then this should solve your compilation issue and also look into Mendix 8 caveats https://github.com/mendix/ux-theming/blob/master/README.md#mendix-8-caveats 

```
// What is the name of the style folder in this theme folder?
var sourceStyleFolder = 'theme/styles/web';  _//Add "/web"_

// What is the name of the style folder in the deployment folder?
var deploymentStyleFolder = 'styles/web';  _//Add "/web"_
```

**Comment by Abhijitbha** [comment]
Thanks for giving the solution so quickly
