### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by tomko80** [mendix/ux-theming#20]
Could we get an update to this? Just installed to a new project and got this...

`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported`

**Comment by JelteMX** [comment]
This is a warning, normal during installation. Updated dependencies in [1.7.0](https://github.com/mendixlabs/ux-theming/releases/tag/v1.7.0), but you don't need to worry about warnings like these.
