### ISSUE TITLE
Issue when using custom page url

### ISSUE THREAD

**Issue by Aelion-MM** [mendix/ux-theming#6]
When configuring a custom page URL  (tested with Mx 6.10.10) the reloading of the styles via browser-sync fail to use the proper path instead of using the root it becomes something like:

/p/homedeveloper/css/custom/custom.css

while it should be

/css/custom/custom.css

Not sure if this has been resolved in later versions of Mx but if not it might be wise to fix it in the scripts available.

Thanks!

**Comment by JelteMX** [comment]
I haven't been able to get this fixed, but we did add a [troubleshooting tip](https://github.com/mendix/ux-theming#i-use-the-dev-task-but-on-reload-it-is-missing-styles).

**Comment by JelteMX** [comment]
Closing issue as we have addressed this in the documentation
