### ISSUE TITLE
Move the source maps to only write to deployment folder

### ISSUE THREAD

**Issue by simo101** [mendix/ux-theming#8]
When optimizing our current site i noticed that the source maps take a large part of the css file size. I suggest that sourcemaps are only used during development, so therefore we should move this line:

[https://github.com/mendix/ux-theming/blob/master/Gulp/_Gulpfile.js#L75](https://github.com/mendix/ux-theming/blob/master/Gulp/_Gulpfile.js#L75)

Below the css write to the source folder and only write it to the deployment folder. This would make the lib.css much more performant.

**Comment by JelteMX** [comment]
Source maps have been written to a separate file (per [1.7.0](https://github.com/mendixlabs/ux-theming/releases/tag/v1.7.0) to a separate folder). When you deploy for production, execute `npm run build` to omit the Sourcemaps from the CSS file entirely. They might still linger in the CSS folder, but are not loaded by the browser (as the CSS does not link to it)
