### ISSUE TITLE
Please update Gulp to v4 to support newest MacOSX updates

### ISSUE THREAD

**Issue by JeroenKesteloo** [mendix/ux-theming#9]
Since the new release of Mac OSX Gulp stopped working. I fixed it locally using https://www.liquidlight.co.uk/blog/article/how-do-i-update-to-gulp-4/ but it would be nice to update the repo with the support for Gulp v4. If it helps I can submit a pull request with the Gulpfile fixes.

**Comment by JelteMX** [comment]
A PR would be very welcome :-)

**Comment by JelteMX** [comment]
Merged in [1.5.0](https://github.com/mendix/ux-theming/releases/tag/v1.5.0)
